sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      env:
        - CC="gcc-7"
    - os: linux
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libglew-dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mingw-w64; fi
script:
  - "sh setup.sh"
