jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      gemfile: Gemfile
      addons:
        homebrew:
          packages:
          - mingw-w64
          - bison
      script:
        - "./build.rb x86_64-w64-mingw32"
    - os: osx
      osx_image: xcode12.2
      gemfile: Gemfile
      addons:
        homebrew:
          packages:
          - bison
      script:
        - "./build.rb macos"
    - os: linux
      dist: focal
      gemfile: Gemfile
      addons:
        apt:
          packages:
            - build-essential
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libglew-dev
            - bison
      script:
        - "./build.rb linux"
    - os: linux
      dist: focal
      gemfile: Gemfile
      addons:
        apt:
          packages:
            - build-essential
            - bison
      script:
        - "./build.rb emscripten"
      before_install:
        - |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ../
    - os: linux
      dist: focal
      gemfile: Gemfile
      addons:
        apt:
          packages:
            - build-essential
            - bison
            - mingw-w64
      script:
        - "./build.rb x86_64-w64-mingw32"
