sudo: false
matrix:
  include:
    - os: osx
    - os: linux
      addons:
        apt:
          packages:
            - build-essential
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libglew-dev
            - bison
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mingw-w64; fi
script:
  - "sh scripts/setup.sh"
