sudo: false
matrix:
  include:
    - os: osx
      osx_image: xcode11.3
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - build-essential
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - libglew-dev
            - bison
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; brew install mingw-w64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      git clone https://github.com/emscripten-core/emsdk.git;
      cd emsdk;
      ./emsdk install latest;
      source ./emsdk_env.sh
      cd -;
    fi
script:
  - "sh scripts/setup.sh"
